//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_PRODUCT
    {
        public T_M_PRODUCT()
        {
            this.T_T_SALES_ORDR_DETAIL = new HashSet<T_T_SALES_ORDR_DETAIL>();
            this.T_T_SALES_RTN_DETAIL = new HashSet<T_T_SALES_RTN_DETAIL>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CAT_ID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual T_M_CATEGORY T_M_CATEGORY { get; set; }
        public virtual ICollection<T_T_SALES_ORDR_DETAIL> T_T_SALES_ORDR_DETAIL { get; set; }
        public virtual ICollection<T_T_SALES_RTN_DETAIL> T_T_SALES_RTN_DETAIL { get; set; }
    }
}
