//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class T_M_CATEGORY
    {
        public T_M_CATEGORY()
        {
            this.T_M_PRODUCT = new HashSet<T_M_PRODUCT>();
        }
    
        [Required]
        public string CAT_ID { get; set; }
        
        [Required]
        public string CAT_NAME { get; set; }
    
        public virtual ICollection<T_M_PRODUCT> T_M_PRODUCT { get; set; }
    }
}
