//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_STORE
    {
        public T_M_STORE()
        {
            this.T_T_SALES_ORDR = new HashSet<T_T_SALES_ORDR>();
        }
    
        public string ST_ID { get; set; }
        public string ST_NAME { get; set; }
        public int ST_AREA { get; set; }
        public string ST_LOCATION { get; set; }
        public int ST_PIC { get; set; }
    
        public virtual T_M_AREA T_M_AREA { get; set; }
        public virtual T_M_PERSON T_M_PERSON { get; set; }
        public virtual ICollection<T_T_SALES_ORDR> T_T_SALES_ORDR { get; set; }
    }
}
