//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_T_SALES_RTN
    {
        public T_T_SALES_RTN()
        {
            this.T_T_SALES_RTN_DETAIL = new HashSet<T_T_SALES_RTN_DETAIL>();
        }
    
        public int RTN_ORDER_ID { get; set; }
        public int SLS_ORDER_ID { get; set; }
        public System.DateTime RTN_ORDER_DT { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DT { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DT { get; set; }
    
        public virtual T_T_SALES_ORDR T_T_SALES_ORDR { get; set; }
        public virtual ICollection<T_T_SALES_RTN_DETAIL> T_T_SALES_RTN_DETAIL { get; set; }
    }
}
