//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_T_SALES_RTN_DETAIL
    {
        public int DETAIL_ID { get; set; }
        public int RTN_ORDER_ID { get; set; }
        public int PRODUCT_ID { get; set; }
        public int QTY { get; set; }
        public decimal RTN_PRICE { get; set; }
    
        public virtual T_M_PRODUCT T_M_PRODUCT { get; set; }
        public virtual T_T_SALES_RTN T_T_SALES_RTN { get; set; }
    }
}
